"""add memory status and sensitivity fields

Revision ID: 53a34c53264e
Revises: 3e56a74fcc48
Create Date: 2026-06-06 19:15:53.467110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '53a34c53264e'
down_revision: Union[str, None] = '3e56a74fcc48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE TYPE memorystatus AS ENUM ('active', 'latent', 'user_reopened')")
    op.alter_column('conversations', 'created_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=False)
    op.alter_column('conversations', 'updated_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=False)
    op.alter_column('messages', 'created_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=False)
    op.add_column('user_memories', sa.Column('status', sa.Enum('active', 'latent', 'user_reopened', name='memorystatus'), nullable=False, server_default='active'))
    op.add_column('user_memories', sa.Column('sensitivity_flag', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('user_memories', sa.Column('sessions_since_surfaced', sa.Integer(), nullable=False, server_default='0'))
    op.drop_column('user_memories', 'is_active')
    op.alter_column('users', 'created_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=False)
    op.alter_column('users', 'updated_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.add_column('user_memories', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('user_memories', 'sessions_since_surfaced')
    op.drop_column('user_memories', 'sensitivity_flag')
    op.drop_column('user_memories', 'status')
    op.alter_column('messages', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('conversations', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('conversations', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    # ### end Alembic commands ###